// Item icons generated by scripts/generate-assets.js from minecraft-assets: flat 16×16 icons, plus
// top/left/right textures for blocks the game shows as 3D cubes. Items newer than the generated version
// have no icon and fall back to their name.
import iconData from '../../generated/itemIcons.json'

type IconData = {
  textures: string[]
  flat: Record<string, number>
  cubes: Record<string, { faces: number[]; tinted: boolean[]; tint?: string }>
}

export type ItemIconInfo =
  { kind: 'flat'; src: string } | { kind: 'cube'; faces: { src: string; tint: string | null }[] }

const data = iconData as IconData

// Items whose texture is stored under a different name in the generated version.
const RENAMED: Record<string, string> = { chain: 'iron_chain', compass: 'recovery_compass' }

export const itemIcon = (name: string): ItemIconInfo | null => {
  const key = data.cubes[name] || data.flat[name] !== undefined ? name : (RENAMED[name] ?? name)
  const cube = data.cubes[key]
  if (cube) {
    return {
      kind: 'cube',
      faces: cube.faces.map((id, index) => ({
        src: data.textures[id],
        tint: cube.tinted[index] ? (cube.tint ?? null) : null,
      })),
    }
  }
  const flat = data.flat[key]
  return flat !== undefined ? { kind: 'flat', src: data.textures[flat] } : null
}
